### ISSUE TITLE
Explanatory Error Message

### ISSUE THREAD

**Issue by hakan-demirli** [PrinceOfPuppers/sync-dl#10]
# Feature Request
It would be user-friendly if missing ffmpeg generated a readable error code.

Currently, if ffmpeg is not installed or not in PATH following error is generated.
```
Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\Scripts\sync-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\__init__.py", line 3, in <module>
    from sync_dl import config as cfg
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\config.py", line 142, in <module>
    setAudioFormat()
  File "C:\Users\USER_NAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\config.py", line 132, in setAudioFormat
    _addIfNotExists(params['postprocessors'], 'FFmpegExtractAudio', {'key': 'FFmpegExtractAudio'})
KeyError: 'postprocessors'
```
# Suggestion
Add an else statement with an explanatory error message to the following part:
https://github.com/PrinceOfPuppers/sync-dl/blob/1c4fe8deec4bf14494780c9d2f67720137366ec2/sync_dl/config.py#L107-L111

**Comment by PrinceOfPuppers** [comment]
It was actually possible to run sync-dl without ffmpeg (not recommended but I have been trying to support it), The most recent addition of the audio format selection broke that, I'll have a fix out later today/tomorrow. 

Thanks for the suggested fix, however I want to continue supporting builds without ffmpeg so unfortunately this wont work. Adding a catch in [def setAudioFormat():](https://github.com/PrinceOfPuppers/sync-dl/blob/1c4fe8deec4bf14494780c9d2f67720137366ec2/sync_dl/config.py#L127) should work.

**Comment by PrinceOfPuppers** [comment]
new version is on pypi:
https://pypi.org/project/sync-dl/2.3.2/

`pip install -U sync-dl`
