### ISSUE TITLE
Multiple Instance Support

### ISSUE THREAD

**Issue by hakan-demirli** [PrinceOfPuppers/sync-dl#7]
Allow multiple instances of sync-dl to run at the same time.

Currently running sync-dl again from another console for another playlist with different folder generates the following error:

```D:\ACTIVE\Music> sync-dl new https://www.youtube.com/playlist?list=someotherplaylist ./playlistname_1
Creating New Playlist Named playlistname_1 from URL: https://www.youtube.com/playlist?list=someotherplaylist
Dowloading song 1/62, Id LEGITSONG_ID
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sync_dl/tmp/05_song_of_the_first_playlist.f303.webm.part'
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\cli.py", line 442, in cli
    args.func(args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\cli.py", line 116, in <lambda>
    new.set_defaults(func = lambda args: newHandler(args, new))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\cli.py", line 178, in newHandler
    newPlaylist(plPath, args.URL)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\commands.py", line 53, in newPlaylist
    success = download(metaData,plPath,songId,-1,numDigits,counter)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\helpers.py", line 117, in download
    if downloadToTmp(songId,num): #returns true if succeeds
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\sync_dl\ytdlWrappers.py", line 92, in downloadToTmp
    os.remove(f"{cfg.tmpDownloadPath}/{f}")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sync_dl/tmp/05_song_of_the_first_playlist.f303.webm.part'
```

Windows 10 20H2
sync-dl version [development branch](https://github.com/PrinceOfPuppers/sync-dl/tree/formats-and-thumbnails)

# How to recreate this:
* open a terminal
* run `sync-dl new https://www.youtube.com/playlist?list=playlist_id ./playlist_0`
* open another terminal
* run `sync-dl new https://www.youtube.com/playlist?list=different_playlist_id ./playlist_1`

# Benefits

yt-dlp and youtube-dl tend to have a slow download speed regardless of the available bandwidth. And both do not support multithreading. So, the best way to speed up the download process is to download multiple playlists at the same time.

**Comment by PrinceOfPuppers** [comment]
Yea, creating a separate tmp directory for each process would solve this. However there is still the restriction of not being able to run sync-dl on the same playlist from two separate processes due to race conditions with the Metadata.

I'll look into supporting two instances editing other playlists
